 CREATE DATABASE mybatis;

 USE mybatis;

 CREATE TABLE USER (
  	ID INT (20) NOT NULL PRIMARY KEY,
  	NAME VARCHAR (30) DEFAULT NULL,
  	PWD VARCHAR (30) DEFAULT NULL
  ) ENGINE = INNODB DEFAULT charset=utf8;

  INSERT INTO USER(ID,NAME,PWD)VALUES(1,'张三','1234'),(2,'李四','1234');