#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <signal.h>
#include <sys/wait.h>

int main(void)
{
	pid_t pid;
	int status;

	pid = fork();
	if(pid < 0) {
		printf("fork error\n");
		return 1;
	}
	else if (0 == pid) {
		/* the child process need to be generated by yourself */
		execl("./child", "child", NULL);
	}
	else {
		signal(SIGCHLD, SIG_IGN);
		sleep(1);
		kill(pid, SIGKILL);
		while(1);
	}
	
	return 0;	
}
