FROM centos:7

RUN yum install -y wget net-tools vim
RUN yum install -y java-1.8.0-openjdk

RUN wget http://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz
RUN tar -xzvf apache-tomcat-8.5.50.tar.gz -C /usr/local/
RUN rm apache-tomcat-8.5.50.tar.gz
COPY tomcat.sh /usr/local/bin/tomcat.sh

CMD /bin/bash /usr/local/bin/tomcat.sh
